name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Application-1 image
      if: ${{ github.event.head_commit.message != '' }}
      run: |
        cd own-microservices/Application-1
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        docker build -t ${{ secrets.DOCKER_USERNAME }}/simpleapp1:$SHORT_SHA .
        docker push ${{ secrets.DOCKER_USERNAME }}/simpleapp1:$SHORT_SHA

    - name: Build and push Application-2 image
      if: ${{ github.event.head_commit.message != '' }}
      run: |
        cd own-microservices/Application-2
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        docker build -t ${{ secrets.DOCKER_USERNAME }}/simpleapp2:$SHORT_SHA .
        docker push ${{ secrets.DOCKER_USERNAME }}/simpleapp2:$SHORT_SHA
