name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]
    paths:
      - 'own-microservices/Application-1/**'
      - 'own-microservices/Application-2/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Application-1 image if changed
      if: ${{ github.event.head_commit.message != '' && contains(join(github.event.commits.*.modified), 'own-microservices/Application-1/') }}
      run: |
        cd own-microservices/Application-1
        docker build -t ${{ secrets.DOCKER_USERNAME }}/simpleapp1:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/simpleapp1:${{ github.sha }}

    - name: Build and push Application-2 image if changed
      if: ${{ github.event.head_commit.message != '' && contains(join(github.event.commits.*.modified), 'own-microservices/Application-2/') }}
      run: |
        cd own-microservices/Application-2
        docker build -t ${{ secrets.DOCKER_USERNAME }}/simpleapp2:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/simpleapp2:${{ github.sha }}
